server:
  port: 8085

kafka:
  topics:
    orders: ${CLOUDKARAFKA_USERNAME}-orders

spring:
  application:
    name: account-microservice

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:accounts
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
