server:
  port: 8086

kafka:
  topics:
    orders: ${CLOUDKARAFKA_USERNAME}-orders

spring:
  application:
    name: user-microservice

  data:
    mongodb:
      uri: mongodb+srv://test:${MONGODB_PASSWORD}@cluster01.aobx7.mongodb.net/userDatabase?retryWrites=true&w=majority
