server:
  port: 8088

kafka:
  topics:
    orders: ${CLOUDKARAFKA_USERNAME}-orders

spring:
  application:
    name: order-microservice

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:orders
    username: sa
    password: password

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
