server:
  port: 8088
# DOESN'T WORK WELL WITH WEBFLUX
#  servlet:
#    context-path: /order

kafka:
  topics:
    orders: ${CLOUDKARAFKA_USERNAME}-orders

spring:
  application:
    name: order-microservice

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

#  kafka:
#    bootstrap-servers: ${CLOUDKARAFKA_SERVERS}
#    properties:
#      security:
#        protocol: SASL_SSL
#      sasl:
#        mechanism: SCRAM-SHA-256
#        jaas:
#          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
